# Generated by Django 5.2.4 on 2025-07-31 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='modalidad_principal',
            field=models.ForeignKey(help_text='Modalidad de pago principal del contrato', on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contratacion.modalidadpago'),
        ),
    ]
