# Generated by Django 5.2.4 on 2025-07-31 18:22

import django.utils.timezone
import django_mongodb_backend.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaRadicada',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('radicacion_id', models.CharField(help_text='ID de la radicación', max_length=24)),
                ('radicacion_info', models.JSONField(default=dict, help_text='Información embebida de la radicación')),
                ('numero_factura', models.CharField(max_length=50)),
                ('fecha_expedicion', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_consultas', models.IntegerField(default=0)),
                ('total_procedimientos', models.IntegerField(default=0)),
                ('total_medicamentos', models.IntegerField(default=0)),
                ('total_otros_servicios', models.IntegerField(default=0)),
                ('total_urgencias', models.IntegerField(default=0)),
                ('total_hospitalizaciones', models.IntegerField(default=0)),
                ('total_recien_nacidos', models.IntegerField(default=0)),
                ('valor_consultas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('valor_procedimientos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('valor_medicamentos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('valor_otros_servicios', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('estado_auditoria', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('GLOSADA', 'Glosada'), ('APROBADA', 'Aprobada')], default='PENDIENTE', max_length=20)),
                ('servicios_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auditoria_facturas',
                'indexes': [models.Index(fields=['radicacion_id', 'numero_factura'], name='auditoria_f_radicac_958a10_idx'), models.Index(fields=['estado_auditoria'], name='auditoria_f_estado__b88fbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='GlosaAplicada',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('radicacion_id', models.CharField(help_text='ID de la radicación', max_length=24)),
                ('numero_radicacion', models.CharField(max_length=50)),
                ('factura_id', models.CharField(help_text='ID de la factura', max_length=24)),
                ('numero_factura', models.CharField(max_length=50)),
                ('fecha_factura', models.DateField()),
                ('servicio_id', models.CharField(help_text='ID del servicio', max_length=24)),
                ('servicio_info', models.JSONField(default=dict, help_text='Información embebida del servicio')),
                ('prestador_info', models.JSONField(default=dict, help_text='Información embebida del prestador')),
                ('tipo_glosa', models.CharField(help_text='Tipo general de glosa (FA, TA, SO, AU, CO, CL, SA)', max_length=2)),
                ('codigo_glosa', models.CharField(help_text='Código específico de la glosa (ej: FA0101)', max_length=10)),
                ('descripcion_glosa', models.TextField(help_text='Descripción del motivo de la glosa')),
                ('valor_servicio', models.DecimalField(decimal_places=2, help_text='Valor original del servicio', max_digits=12)),
                ('valor_glosado', models.DecimalField(decimal_places=2, help_text='Valor glosado', max_digits=12)),
                ('porcentaje_glosa', models.DecimalField(decimal_places=2, help_text='Porcentaje de la glosa sobre el valor del servicio', max_digits=5)),
                ('observaciones', models.TextField(help_text='Observaciones detalladas del auditor')),
                ('estado', models.CharField(default='APLICADA', help_text='Estado actual de la glosa', max_length=20)),
                ('auditor_info', models.JSONField(default=dict, help_text='Información del auditor que aplicó la glosa')),
                ('fecha_aplicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_servicio', models.CharField(help_text='Tipo de servicio glosado (CONSULTA, PROCEDIMIENTO, etc.)', max_length=20)),
                ('excede_valor_servicio', models.BooleanField(default=False, help_text='Indica si el valor glosado excede el valor del servicio')),
                ('historial_cambios', models.JSONField(blank=True, default=list, help_text='Historial de cambios en la glosa')),
                ('respuestas', models.JSONField(blank=True, default=list, help_text='Lista de respuestas del prestador')),
                ('estadisticas', models.JSONField(blank=True, default=dict, help_text='Estadísticas agregadas de la glosa')),
            ],
            options={
                'verbose_name': 'Glosa Aplicada',
                'verbose_name_plural': 'Glosas Aplicadas',
                'db_table': 'auditoria_glosa_aplicada',
                'ordering': ['-fecha_aplicacion'],
                'indexes': [models.Index(fields=['numero_radicacion', 'estado'], name='auditoria_g_numero__9018f5_idx'), models.Index(fields=['numero_factura'], name='auditoria_g_numero__f7740e_idx'), models.Index(fields=['codigo_glosa'], name='auditoria_g_codigo__42f7ba_idx'), models.Index(fields=['fecha_aplicacion'], name='auditoria_g_fecha_a_1964c4_idx'), models.Index(fields=['estado'], name='auditoria_g_estado_1acb5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServicioFacturado',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('factura_id', models.CharField(help_text='ID de la factura', max_length=24)),
                ('factura_info', models.JSONField(default=dict, help_text='Información embebida de la factura')),
                ('tipo_servicio', models.CharField(choices=[('CONSULTA', 'Consulta'), ('PROCEDIMIENTO', 'Procedimiento'), ('MEDICAMENTO', 'Medicamento'), ('OTRO_SERVICIO', 'Otro Servicio'), ('URGENCIA', 'Urgencia'), ('HOSPITALIZACION', 'Hospitalización'), ('RECIEN_NACIDO', 'Recién Nacido')], max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad', models.IntegerField(default=1)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('condicion_egreso', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=5, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo_biologico', models.CharField(blank=True, max_length=1, null=True)),
                ('detalle_json', models.JSONField(blank=True, null=True)),
                ('tiene_glosa', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'auditoria_servicios',
                'indexes': [models.Index(fields=['factura_id', 'tipo_servicio'], name='auditoria_s_factura_56863f_idx'), models.Index(fields=['codigo'], name='auditoria_s_codigo_dd7144_idx')],
            },
        ),
    ]
