# Generated by Django 5.2.4 on 2025-07-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciofacturado',
            name='glosas_aplicadas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de glosas aplicadas a este servicio'),
        ),
    ]
