# Generated by Django 5.2.4 on 2025-07-30 22:17

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Glosa',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('radicacion_id', models.CharField(db_index=True, max_length=24)),
                ('numero_radicado', models.CharField(db_index=True, max_length=50)),
                ('prestador_nit', models.CharField(db_index=True, max_length=20)),
                ('prestador_nombre', models.CharField(max_length=200)),
                ('factura_numero', models.CharField(db_index=True, max_length=50)),
                ('factura_prefijo', models.CharField(blank=True, max_length=10)),
                ('codigo_glosa', models.CharField(db_index=True, max_length=6)),
                ('categoria_glosa', models.CharField(choices=[('FA', 'Facturación'), ('TA', 'Tarifas'), ('SO', 'Soportes'), ('AU', 'Autorizaciones'), ('CO', 'Cobertura'), ('CL', 'Calidad'), ('SA', 'Seguimiento de Acuerdos')], db_index=True, max_length=2)),
                ('descripcion_glosa', models.TextField()),
                ('consecutivo_servicio', models.CharField(max_length=20)),
                ('codigo_servicio', models.CharField(max_length=20)),
                ('descripcion_servicio', models.TextField()),
                ('valor_glosado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_aceptado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_objetado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('FORMULADA', 'Formulada'), ('NOTIFICADA', 'Notificada'), ('RESPONDIDA_1', 'Respondida (Primera vez)'), ('RATIFICADA', 'Ratificada por EPS'), ('ACEPTADA_PARCIAL', 'Aceptada Parcialmente'), ('ACEPTADA_TOTAL', 'Aceptada Totalmente'), ('OBJETADA', 'Objetada por Prestador'), ('CONCILIACION', 'En Conciliación'), ('CERRADA', 'Cerrada')], db_index=True, default='FORMULADA', max_length=20)),
                ('fecha_formulacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_notificacion', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fecha_limite_respuesta', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fecha_respuesta_prestador', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite_ratificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_ratificacion_eps', models.DateTimeField(blank=True, null=True)),
                ('respuesta_extemporanea', models.BooleanField(default=False)),
                ('aceptacion_tacita_prestador', models.BooleanField(default=False)),
                ('glosa_injustificada', models.BooleanField(default=False)),
                ('observaciones_auditoria', models.TextField(blank=True)),
                ('observaciones_respuesta', models.TextField(blank=True)),
                ('observaciones_ratificacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='glosas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'glosas',
                'ordering': ['-fecha_formulacion'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaGlosa',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('codigo_respuesta', models.CharField(choices=[('RE9501', 'Devolución extemporánea'), ('RE9502', 'Glosa extemporánea'), ('RE9601', 'Devolución injustificada al 100%'), ('RE9602', 'Glosa injustificada al 100%'), ('RE9701', 'Devolución totalmente aceptada'), ('RE9702', 'Glosa totalmente aceptada'), ('RE9801', 'Glosa parcialmente aceptada y subsanada parcialmente'), ('RE9901', 'Glosa no aceptada y subsanada en su totalidad'), ('RE2201', 'Respuesta a devolución extemporánea'), ('RE2202', 'Respuesta a glosa extemporánea')], db_index=True, max_length=6)),
                ('descripcion_respuesta', models.TextField()),
                ('valor_aceptado_prestador', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_objetado_prestador', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_subsanado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('documentos_soporte', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, help_text='Rutas de documentos soporte adjuntos')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('es_extemporanea', models.BooleanField(default=False)),
                ('glosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='glosas.glosa')),
                ('respondido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_glosas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'respuestas_glosas',
                'ordering': ['-fecha_respuesta'],
            },
        ),
        migrations.CreateModel(
            name='RatificacionGlosa',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('ACEPTAR_RESPUESTA', 'Aceptar Respuesta del Prestador'), ('RATIFICAR_GLOSA', 'Ratificar Glosa Original'), ('ACEPTAR_PARCIAL', 'Aceptar Parcialmente'), ('CONCILIACION', 'Enviar a Conciliación')], db_index=True, max_length=20)),
                ('valor_final_aceptado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_final_glosado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('justificacion', models.TextField()),
                ('fecha_ratificacion', models.DateTimeField(auto_now_add=True)),
                ('es_extemporanea', models.BooleanField(default=False)),
                ('glosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratificaciones', to='glosas.glosa')),
                ('ratificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratificaciones_glosas', to=settings.AUTH_USER_MODEL)),
                ('respuesta_glosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratificaciones', to='glosas.respuestaglosa')),
            ],
            options={
                'db_table': 'ratificaciones_glosas',
                'ordering': ['-fecha_ratificacion'],
            },
        ),
        migrations.AddIndex(
            model_name='glosa',
            index=models.Index(fields=['radicacion_id'], name='glosas_radicac_b9efc9_idx'),
        ),
        migrations.AddIndex(
            model_name='glosa',
            index=models.Index(fields=['numero_radicado'], name='glosas_numero__f7bb03_idx'),
        ),
        migrations.AddIndex(
            model_name='glosa',
            index=models.Index(fields=['prestador_nit'], name='glosas_prestad_af30bf_idx'),
        ),
        migrations.AddIndex(
            model_name='glosa',
            index=models.Index(fields=['factura_numero'], name='glosas_factura_c71535_idx'),
        ),
        migrations.AddIndex(
            model_name='glosa',
            index=models.Index(fields=['codigo_glosa'], name='glosas_codigo__ca8b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='glosa',
            index=models.Index(fields=['categoria_glosa'], name='glosas_categor_be0c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='glosa',
            index=models.Index(fields=['estado'], name='glosas_estado_4208f8_idx'),
        ),
        migrations.AddIndex(
            model_name='glosa',
            index=models.Index(fields=['fecha_formulacion'], name='glosas_fecha_f_e4fae8_idx'),
        ),
        migrations.AddIndex(
            model_name='glosa',
            index=models.Index(fields=['fecha_limite_respuesta'], name='glosas_fecha_l_971879_idx'),
        ),
        migrations.AddIndex(
            model_name='glosa',
            index=models.Index(fields=['aceptacion_tacita_prestador'], name='glosas_aceptac_e6d7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='glosa',
            index=models.Index(fields=['glosa_injustificada'], name='glosas_glosa_i_fc3119_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestaglosa',
            index=models.Index(fields=['glosa'], name='respuestas__glosa_i_a79d89_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestaglosa',
            index=models.Index(fields=['codigo_respuesta'], name='respuestas__codigo__6f558a_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestaglosa',
            index=models.Index(fields=['fecha_respuesta'], name='respuestas__fecha_r_411762_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestaglosa',
            index=models.Index(fields=['es_extemporanea'], name='respuestas__es_exte_2c0ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='ratificacionglosa',
            index=models.Index(fields=['glosa'], name='ratificacio_glosa_i_56104b_idx'),
        ),
        migrations.AddIndex(
            model_name='ratificacionglosa',
            index=models.Index(fields=['decision'], name='ratificacio_decisio_f17300_idx'),
        ),
        migrations.AddIndex(
            model_name='ratificacionglosa',
            index=models.Index(fields=['fecha_ratificacion'], name='ratificacio_fecha_r_88e9a0_idx'),
        ),
        migrations.AddIndex(
            model_name='ratificacionglosa',
            index=models.Index(fields=['es_extemporanea'], name='ratificacio_es_exte_e5f2da_idx'),
        ),
    ]
